### ISSUE TITLE
Resolve JsonSchema's allOf pointer

### ISSUE THREAD

**Issue by kojidev** [thephpleague/json-reference#25]
Hi, whatever I'm about to say might be dump due to my little experience with Json Schema and Json Reference but anyway, I have documents like this:

> foo.yaml
```YAML
type: object
properties:
  logo:
    allOf:
    - { ref: imageLink.yaml }
    - nullable: true
```

> bar.yaml
```YAML
type: object
properties:
  logo: { $ref: foo.yaml#/properties/logo/nullable }
```

and obviously it fails [here](https://github.com/thephpleague/json-reference/blob/cecf8d4e38e1c9eda179a3798b5cac81b3f907c9/src/Pointer.php#L41), since there's no Json Schema's allOf/oneOf etc resolving strategies.

What I thought is possible is:

1. Resolve it myself by merging beforehand, but I don't really want to as I want to leave original document structure.
2. Hardcode additional login in `Pointer::traverse` method
3. Delegate traversing pointer to a `PointerTraverserInterface' so it be possible to compose desirable behavior.

What you think?

P.S. It is not actually Json Schema, more like OpenAPI Schema Object (nullable field), but it doesn't matter in this context)
